Revamp scenarios and add azure code

diff --git a/assets/templates/provision/start_hashicups_db.sh.tmpl b/assets/templates/provision/start_hashicups_db.sh.tmpl
--- a/assets/templates/provision/start_hashicups_db.sh.tmpl
+++ b/assets/templates/provision/start_hashicups_db.sh.tmpl
@@ -1,8 +1,111 @@
+#!/bin/bash
+
 #!/usr/bin/env bash
+
+## Service file to start HashiCups services in the different VM based scenarios.
+## For production environments it is recommended to use systemd service files, 
+## this file is more complex than needed in order to take into account all possible
+## situation an HashiCups service might get started in the different use-cases.
+
+## Possible uses:
+## -----------------------------------------------------------------------------
+## service.sh                       -   [Compatibility mode] Starts the service on all available interfaces  
+## service.sh local                 -   [Compatibility mode] Starts the service on localhost interface
+## service.sh start                 -   Starts the service using hostnames for upstream services
+## service.sh start --local         -   Starts the service on localhost interface
+## service.sh start --hostname      -   Starts the service using hostnames for upstream services
+## service.sh start --consul        -   Starts the service using Consul service name for upstream services (using LB functionality)
+## service.sh start --consul-node   -   Starts the service using Consul node name for upstream services
+## service.sh stop                  -   Stops the service
+## service.sh reload                -   Reload the service without changing the configuration files
+## service.sh reload --local        -   Reload the service without changing the configuration files. If variables need to be set, are set on localhost.
+
+echo '# ------------------------------------ #'
+echo '|        HashiCups DB service          |'
+echo '# ------------------------------------ #'
+
+## ----------
+## Variables
+## -----------------------------------------------------------------------------
+
+## If set to true the service is started locally
+SERVICE_MESH=false
+
+## ----------
+## Stop pre-existing instances.
+## -----------------------------------------------------------------------------
+echo "Stop pre-existing instances."
 
 docker rm -f hashicups-db
 
-if [ "$${1}" == local ]; then
+sleep 1
+
+## -----------------------------------------------------------------------------
+
+## ----------
+## Check script command
+## -----------------------------------------------------------------------------
+case "$${1}" in
+    "")
+        echo "EMPTY - Start services on all interfaces."
+        ;;
+    "local")
+        echo "LOCAL - Start services on local interface."
+        SERVICE_MESH=true
+        ;;
+    "start")
+        echo "START - Start services on all interfaces."
+        case "$${2}" in
+        ""|"--hostname")
+            echo "START - Start services on all interfaces using hostnames for upstream services."
+            ;;
+        "--local")
+            echo "START LOCAL - Start services on local interface."
+            SERVICE_MESH=true
+            ;;
+        "--consul")
+            echo "START CONSUL - Starts the service using Consul service name for upstream services (using LB functionality)."
+            echo "NOT APPLICABLE FOR THIS SERVICE - No Upstreams to define."
+            ;;
+        "--consul-node")
+            echo "START CONSUL - Starts the service using Consul node name for upstream services."
+            echo "NOT APPLICABLE FOR THIS SERVICE - No Upstreams to define."
+            ;;
+        *) echo "$${0} $${1}: error - unrecognized option $${2}" 1>&2; exit 2;;
+        esac 
+        ;;
+    "stop")
+        echo "Service instance stopped." 
+        exit 0
+        ;;
+    "reload")
+        echo "RELOAD - Start services on all interfaces."
+        case "$${2}" in
+            "")
+                echo "RELOAD - Reload the service without changing the configuration files"
+                echo "NOT APPLICABLE FOR THIS SERVICE - A full restart is going to be performed."
+                ;;
+            "--local")
+                echo "RELOAD LOCAL - Reload the service without changing the configuration files. If variables need to be set, are set on localhost."
+                echo "NOT APPLICABLE FOR THIS SERVICE - A full restart, on local interface, is going to be performed."
+                SERVICE_MESH=true
+                ;;
+        
+            *) echo "$${0} $${1}: error - unrecognized option $${2}" 1>&2; exit 2;;
+        esac
+        ;;
+    *) echo "$${0}: error - unrecognized option $${1}" 1>&2; exit 1;;
+esac
+
+## -----------------------------------------------------------------------------
+
+
+## ----------
+## Start instances.
+## -----------------------------------------------------------------------------
+echo "Start service instance."
+
+if [ "$${SERVICE_MESH}" == true ]; then
     # Start Application on localhost
     NETWORK="--publish 127.0.0.1:5432:5432"
 else
@@ -17,3 +120,5 @@ docker run \
   --env POSTGRES_PASSWORD=hashicups_pwd \
   --env POSTGRES_USER=hashicups \
   --name hashicups-db hashicorpdemoapp/product-api-db:${VERSION}
+
+## -----------------------------------------------------------------------------
